### ISSUE TITLE
If punched you lose hat/helmet

### ISSUE THREAD

**Issue by XvenDeR** [andristum/dpclothing#10]
Hi, great script!
A suggestion: Would be great if the script would recognize that you had a hat or helmet and would be able to put it back on.

**Comment by andristum** [comment]
Would love to do this, but as that feature would require a framework implementation i'm a little limited on how i can make it work.
Since i dont want to tie this resource down to user having to use ESX or some other popular framework.
For now what one can do is simply disable the function of /hat and use another resource, then the GUI will still  be able to use /hat, it just wont show blue when it has a saved one.

**Comment by XvenDeR** [comment]
good solution, thanks.
