### ISSUE TITLE
Not an issue but request

### ISSUE THREAD

**Issue by FBFezz** [andristum/dpclothing#5]
Say if an npc hits you and knocks your glasses off, you cant re equip it at all unless you go back to clothing store and buy it. What if the Y menu lets you put them back on when they fall off (this is in the esx_accessories script)

**Comment by andristum** [comment]
Trying to find a way of doing this that doesnt rely on the person installing the script having esx/esx_skin/esx_accesories.
Dont want to tie this resource down to just the servers using ESX.
I'll do some experimenting.

**Comment by FBFezz** [comment]
Ahh ok, ill mess around with it as well and let you know if i figure it out but I'm not that good at doing this stuff tbh

**Comment by FBFezz** [comment]
Not sure if this helps at all but i think the way it saves with esx accessories is using the database to save the clothing, ill attach a screenshot of what i mean

![image](https://user-images.githubusercontent.com/43589668/84689582-18a9cf80-af39-11ea-9607-af03b6e857d0.png)

**Comment by FBFezz** [comment]
Issue: When i take something off of myself and go into say an esx menu it puts clothes back on (Video explains it better)

https://streamable.com/9nl62c

**Comment by andristum** [comment]
I've thought about doing a SQL thing to fix these issues, however there is no universal fix for it since so many servers use different forms of framework / even different resources to manage the players skin/clothing.
I have personally fixed this for my own framework, i'll probably end up leaving in the functions/events whenever i release another update to this, so ESX/VRP/other framework developers can use that, but for now im closing this issue because there isnt one solid fix i can think of.

**Comment by FBFezz** [comment]
Ah ok thank you and did you read what I said about the issue with the esx menu basically resetting my clothes?
